import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Grid from "@mui/material/Grid";
import {RepositorySelector} from "@/app/RepositorySelector";
import {LogoutLink} from "@/app/LogoutLink";
import Container from "@mui/material/Container";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Grid container spacing={1} size={12}>
            <Grid padding={3} size={12} justifyContent='center' alignItems='center' display='flex' bgcolor='#f5f5f5'>
                <Grid size={11} justifyContent='center' display='flex'>
                    <RepositorySelector/>
                </Grid>
                <Grid size={1}>
                    <LogoutLink/>
                </Grid>
            </Grid>
            <Grid size={12}>
                <Container style={{padding: '10px'}}>
                    {children}
                </Container>
            </Grid>
        </Grid>
        </body>
        </html>
    );
}
